# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: THE ULTRAVOID
email: gulsuma251@gmail.com
description: STORIES FROM THE DISTANT FUTURE

baseurl: "" #e.g. /safarnama, /blog. Dont forget the '/'.
url: "http://hemangsk.github.io" # the base hostname & protocol for your site
twitter_username: ultravoid5
github_username:  ultravoid

# Build settings
markdown: kramdown
